### PR TITLE
 Implement Preview Service

### LINKED ISSUE #28: Provide Preview Service
I am reconciling against local CSV files with ambiguous data in the search column and without ids from external systems (Wikidata...).

| ID | Search Column  | Additional Data |
| -- |----------------- | ---------------- |
| 1  | John Doe           | 1970-01-01      |
| 2  | John Doe           | 2020-01-01      |
| ...  | ...                       | ...                       |

To identify the correct match from the Reconciliation API I have to manually check the proposed results against the data in the CSV files. To speed this process up I would prefer to use a Preview Service as defined in the [Reconciliation Service API Specification](https://reconciliation-api.github.io/specs/latest/#preview-service).

### PR DESCRIPTION
**Pull request by b2m**
This solution implements a very simple Preview Service that will render the matched row from the CSV file as [description list](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl).

Note that I also added a generic `.gitignore` file in a separate commit. I know that many developers nowadays are using global `.gitignore` files, but providing a `.gitignore` (and a [.editorconfig](https://editorconfig.org/)) in the repository is much appreciated by new contributors.

Closes #28.

### CODE REVIEW

**Comment by gitonthescene** [comment]
Thanks for this.  Let me give it a spin and I'll post back.  In the meantime would you mind adding an issue and referring to it in the original post as per the [contributing guidelines](https://github.com/gitonthescene/csv-reconcile/blob/023708e0da3ffd27226e0a5238131622e3addb47/CONTRIBUTING.org)?

FWIW, I think this is a great idea.  I had always pictured people making csv files with references to data taken from other services like Wikidata whence the preview service can be borrowed, but I completely get how this is useful in the more general case.

**Comment by gitonthescene** [comment]
Looks good.  I've merged this now.  Sorry for the delay.  FWIW, I think I'm missing a dependency between the steps in my GitHub actions and that explains the failed test.  I'll have to look at that.

Also, as you've probably noticed this is on the develop branch.  I guess I should do a release soon.  Can I ask your opinion on whether you felt the change to the command line interface was easy enough to adapt to?

**Comment by gitonthescene** [comment]
Oohh..  I also noticed that when the service is shut down then hovering over it shows "unable to connect".  Since these are imagined to be temporary services, that's kind of annoying.  Also, since you may be making many temporary services running on the same port the preview service may not make sense if it's showing data from the current service.

I'm not sure what the right thing to do is.  What do you think about not having this on by default?  You can always add it by supplying a config to point to it.  This sort of side steps the issue until we come up with a better idea.

**Comment by b2m** [comment]
> Can I ask your opinion on whether you felt the change to the command line interface was easy enough to adapt to?

It took me a second to get used to the switch. But I see the further potential of the new approach.

Going to adress the other comment in #28 .

**Pull request merged**
